Support more cases for RCS1151
dotnet/roslynator pull request #1152
Opened 2023-08-06 19:02 UTC by jamesHargreaves12

Add support for a couple of cases:
1) Casts where the type is identical :
```
int x = 1;
int y = (int)x;
```

2) Linq Cast from a type that implements IEnumerable<T> and chained to a method that receives an IEnumerable<T>.
```
Regex.Matches(s, ".*")
                .Cast<Match>()
                .Select(x => x.Value);
```

2023-08-07 23:18 UTC, JosefPihrt commented
@jamesHargreaves12 pipeline failed.

2023-08-09 19:30 UTC, jamesHargreaves12 commented
Cannot reproduce the pipeline error locally.

2023-08-10 10:08 UTC, JosefPihrt requested changes

2023-08-10 10:08 UTC, JosefPihrt commented on src/Analyzers/CSharp/Analysis/RemoveRedundantCastAnalyzer.cs
> +                 || chainedMethodReceiverType.OriginalDefinition.IsIEnumerableOfT() != true)
```suggestion
        else if (invocationExpression.Parent is not MemberAccessExpressionSyntax { Parent: InvocationExpressionSyntax chainedMethodInvocation }
            || semanticModel.GetSymbol(chainedMethodInvocation, cancellationToken) is not IMethodSymbol { ReceiverType: INamedTypeSymbol chainedMethodReceiverType }
            || !chainedMethodReceiverType.OriginalDefinition.IsIEnumerableOfT())
```

2023-11-27 23:50 UTC, closed without merging