RCS1268 - Simplify Numeric Comparison
dotnet/roslynator pull request #1405
Opened 2024-02-17 21:46 UTC by jakubreznak

fixes #1394

2024-02-20 00:00 UTC, josefpihrt commented
Is this PR ready for review? If so, can you request a review?

2024-02-20 16:38 UTC, jakubreznak commented
Yes, the PR is ready for review. Could you please review my code? Thanks

(I wanted to add to reviewers, but i cannot.)

2024-02-20 16:48 UTC, josefpihrt commented
I see, I didn't know you cannot request a review.

So, just to be clear, what do you see in the UI?

I see this:

![image](https://github.com/dotnet/roslynator/assets/11931318/d9773256-f612-4032-a88f-5a7d7753edaa)

2024-02-20 17:09 UTC, jakubreznak commented
![image](https://github.com/dotnet/roslynator/assets/56341176/c6a67a6b-6e28-437a-92ba-866222604da4)

I see this.

2024-02-20 17:20 UTC, josefpihrt commented
Thanks for the screenshot. It's probably because the repo is part of dotnet organization.

2024-02-23 16:43 UTC, josefpihrt requested changes

2024-02-23 16:43 UTC, josefpihrt commented on src/Analyzers.xml
> +    <Title>Simplify numeric comparison expression</Title>
Please remove "expression" at the end.

2024-02-23 16:43 UTC, josefpihrt commented on src/Analyzers/CSharp/Analysis/SimplifyNumericComparisonAnalyzer.cs
> +            || (leftExpression.Kind() == SyntaxKind.SubtractExpression && rightExpression.IsNumericLiteralExpression("0")))
Use `IsKind` instead of `Kind`

2024-02-23 16:43 UTC, josefpihrt commented on src/Analyzers.CodeFixes/CSharp/CodeFixes/BinaryExpressionCodeFixProvider.cs
> +            switch (kind)
You can use switch expression here.

```
kind = kind switch
{
    ....
}
```

2024-02-25 17:46 UTC, jakubreznak commented
Thank you for the code review and your suggestions. I have implemented the changes you suggested.

2024-02-25 21:56 UTC, josefpihrt approved these changes

2024-02-26 11:51 UTC, merged

2024-02-26 11:51 UTC, josefpihrt commented
@jakubreznak Nice PR, thanks!

2024-03-14 21:32 UTC, BenjaminBrienen commented
https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1268 is a 404

2024-03-15 08:37 UTC, josefpihrt commented
@BenjaminBrienen Changelog contains incorrect information that this analyzer is part of 4.11.0 but it haven't been released yet. Changelog will be fixed as a part of next release.