When reportDiagnostic is Default return descriptor default severity
dotnet/roslynator pull request #1411
Opened 2024-02-22 10:09 UTC by jsliwinski

2024-02-22 11:23 UTC, josefpihrt commented
Hi,

Thanks for the PR. I'm able to reproduce the bug.

2024-02-22 11:26 UTC, josefpihrt requested changes
Please update changelog.

2024-02-22 11:26 UTC, josefpihrt commented on src/Core/Extensions/DiagnosticsExtensions.cs
> +                return (reportDiagnostic == Microsoft.CodeAnalysis.ReportDiagnostic.Default)
I just verified that not only this condition can return `Default` but also the one above and below. I would suggest to put these three `if`s to separate local method.

2024-02-23 10:51 UTC, jsliwinski commented
@dotnet-policy-service agree

2024-02-23 13:25 UTC, josefpihrt approved these changes

2024-02-23 13:26 UTC, merged

2024-02-23 13:27 UTC, josefpihrt commented
@jsliwinski Thank you for the contribution!