RCS1246 - update, added Last
dotnet/roslynator pull request #1436
Opened 2024-04-05 15:59 UTC by jakubreznak

fixes #1426

2024-04-07 06:28 UTC, josefpihrt requested changes

2024-04-07 06:28 UTC, josefpihrt commented on ChangeLog.md
> +- Update - add Last [RCS1246](https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1246) ([PR](https://github.com/dotnet/roslynator/pull/1431))
Fix PR number

2024-04-07 06:28 UTC, josefpihrt commented on src/Analyzers/CSharp/Analysis/InvocationExpressionAnalyzer.cs
> +                                        && UseElementAccessAnalysis.IsFixableLast(invocationInfo, context.SemanticModel, context.CancellationToken))
Method `IsFixableLast` should contain a check if current compilation supports C# 8.0 or higher

2024-04-15 19:57 UTC, josefpihrt approved these changes

2024-04-15 19:57 UTC, merged

2024-04-15 19:57 UTC, josefpihrt commented
👍

2024-04-15 19:58 UTC, josefpihrt commented
Thanks!

2024-04-22 15:51 UTC, KavenBreton-eaton commented
This is not usable for .Net Framework projects. Was this intended?

2024-04-22 19:27 UTC, josefpihrt commented
@KavenBreton-eaton Could you please report it as a bug?